export interface Question {
  q: string;
  correct: string;
  wrong: string[];
}

export interface Fact {
  text: string;
  true: boolean;
}

export interface EmojiPuzzle {
  emojis: string[];
  answer: string;
}

export const CURIOSITY_DB: Question[] = [
  { q: "Qual è l'animale che dorme di più al giorno?", correct: "Koala", wrong: ["Gatto", "Leone", "Pipistrello", "Tartaruga", "Bradipo"] },
  { q: "Quale paese ha più isole al mondo?", correct: "Svezia", wrong: ["Indonesia", "Filippine", "Giappone", "Grecia", "Finlandia"] },
  { q: "Qual è il metallo più abbondante nella crosta terrestre?", correct: "Alluminio", wrong: ["Rame", "Oro", "Argento", "Titanio", "Al"] },
  { q: "Quale organo umano consuma più energia?", correct: "Cervello", wrong: ["Cuore", "Polmoni", "Stomaco", "Reni", "Fegato"] },
  { q: "Qual è l'oceano più profondo?", correct: "Pacifico", wrong: ["Indiano", "Artico", "Antartico", "Mediterraneo", "Fossa delle Marianne"] },
  { q: "Quale animale ha il morso più potente?", correct: "Coccodrillo", wrong: ["Squalo", "Leone", "Orso", "Lupo", "Ippopotamo"] },
  { q: "Quale pianeta ha più lune?", correct: "Saturno", wrong: ["Marte", "Urano", "Nettuno", "Terra", "Giove"] },
  { q: "Quale frutto contiene più vitamina C?", correct: "Guava", wrong: ["Arancia", "Limone", "Fragola", "Mango", "Kiwi"] },
  { q: "Quale è il fiume più lungo del mondo?", correct: "Nilo", wrong: ["Mississippi", "Yangtze", "Danubio", "Gange", "Amazzoni"] },
  { q: "Quale animale può vivere più a lungo?", correct: "Tartaruga", wrong: ["Elefante", "Pappagallo", "Aquila", "Corvo", "Balena"] },
  { q: "Quale paese produce più caffè al mondo?", correct: "Brasile", wrong: ["Colombia", "Etiopia", "Italia", "Kenya", "Vietnam"] },
  { q: "Qual è l'elemento chimico più leggero?", correct: "Idrogeno", wrong: ["Litio", "Carbonio", "Ossigeno", "Azoto", "H"] },
  { q: "Quale animale ha il cuore più grande?", correct: "Balenottera azzurra", wrong: ["Giraffa", "Cavallo", "Gorilla", "Ippopotamo", "Balena"] },
  { q: "Quale città è la più popolosa al mondo?", correct: "Tokyo", wrong: ["New York", "Londra", "Pechino", "San Paolo", "Delhi"] },
  { q: "Quale animale è il più veloce in volo?", correct: "Falco pellegrino", wrong: ["Aquila", "Colibrì", "Albatros", "Gufo", "Rondone"] },
  { q: "Quale paese ha la forma di uno stivale?", correct: "Italia", wrong: ["Portogallo", "Cile", "Giappone", "Norvegia", "Bel Paese"] },
  { q: "Quale osso è il più piccolo del corpo umano?", correct: "Staffa", wrong: ["Rotula", "Coccige", "Femore", "Falange", "Orecchio"] },
  { q: "Quale sport è il più praticato al mondo?", correct: "Calcio", wrong: ["Tennis", "Basket", "Cricket", "Golf", "Nuoto"] },
  { q: "Quale materiale naturale è il più duro?", correct: "Diamante", wrong: ["Quarzo", "Rubino", "Granito", "Topazio", "Carbonio"] },
  { q: "Quale gas compone la maggior parte dell'atmosfera?", correct: "Azoto", wrong: ["Anidride carbonica", "Argon", "Elio", "Metano", "N2"] },
  { q: "Qual è il pianeta più caldo del sistema solare?", correct: "Venere", wrong: ["Marte", "Giove", "Saturno", "Terra", "Secondo pianeta"] },
  { q: "Quale animale non può saltare?", correct: "Elefante", wrong: ["Rinoceronte", "Giraffa", "Cammello", "Maiale", "Ippopotamo"] },
  { q: "Quanti cuori ha un polpo?", correct: "3", wrong: ["1", "2", "4", "8", "Tre"] },
  { q: "Qual è l'unico uccello che può volare all'indietro?", correct: "Colibrì", wrong: ["Rondine", "Passero", "Aquila", "Pappagallo", "Hummingbird"] },
  { q: "Quale paese ha inventato la pizza?", correct: "Italia", wrong: ["USA", "Cina", "Egitto", "Turchia", "Napoli"] },
  { q: "Qual è il deserto più grande del mondo?", correct: "Antartide", wrong: ["Gobi", "Kalahari", "Atacama", "Arabico", "Sahara"] },
  { q: "Quale vitamina viene prodotta dal sole?", correct: "Vitamina D", wrong: ["Vitamina C", "Vitamina A", "Vitamina B12", "Vitamina E", "Calciferolo"] },
  { q: "Qual è il muscolo più forte del corpo umano?", correct: "Massetere", wrong: ["Bicipite", "Quadricipite", "Cuore", "Lingua", "Gluteo"] },
  { q: "Quale città è chiamata la città eterna?", correct: "Roma", wrong: ["Parigi", "Londra", "Gerusalemme", "Il Cairo", "L'Urbe"] },
  { q: "Quante ossa ha un neonato rispetto a un adulto?", correct: "Di più", wrong: ["Di meno", "Uguali", "La metà", "Zero", "Circa 300"] },
  { q: "Qual è l'animale più veloce sulla terra?", correct: "Ghepardo", wrong: ["Leone", "Cavallo", "Tigre", "Struzzo", "Cheetah"] },
  { q: "Quale pianeta è conosciuto come il pianeta rosso?", correct: "Marte", wrong: ["Giove", "Saturno", "Urano", "Nettuno", "Quarto pianeta"] },
  { q: "Qual è la lingua più parlata al mondo?", correct: "Inglese", wrong: ["Spagnolo", "Arabo", "Hindi", "Francese", "Cinese Mandarino"] },
  { q: "Qual è il metallo più prezioso?", correct: "Rodio", wrong: ["Oro", "Argento", "Palladio", "Iridio", "Platino"] },
  { q: "Quale animale ha la gestazione più lunga?", correct: "Elefante", wrong: ["Balena", "Giraffa", "Rinoceronte", "Umano", "Squalo"] },
  { q: "Qual è la capitale del Giappone?", correct: "Tokyo", wrong: ["Kyoto", "Osaka", "Seoul", "Pechino", "Edo"] },
  { q: "Quale inventore ha creato la lampadina?", correct: "Thomas Edison", wrong: ["Nikola Tesla", "Alexander Bell", "Isaac Newton", "Albert Einstein", "Joseph Swan"] },
  { q: "Qual è l'oceano più piccolo?", correct: "Artico", wrong: ["Indiano", "Pacifico", "Atlantico", "Mediterraneo", "Polo Nord"] },
  { q: "Quale animale è il simbolo dell'Australia?", correct: "Canguro", wrong: ["Koala", "Vombato", "Ornitorinco", "Dingo", "Emu"] },
  { q: "Qual è il monte più alto del mondo?", correct: "Everest", wrong: ["Kilimangiaro", "Monte Bianco", "Ande", "K2", "Himalaya"] },
  { q: "Quale pittore ha dipinto la Gioconda?", correct: "Leonardo da Vinci", wrong: ["Michelangelo", "Raffaello", "Donatello", "Botticelli", "Leonardo"] },
  { q: "Qual è il continente più freddo?", correct: "Antartide", wrong: ["Artide", "Asia", "Europa", "America", "Polo Sud"] },
  { q: "Quale strumento misura la temperatura?", correct: "Termometro", wrong: ["Barometro", "Igrometro", "Anemometro", "Sismografo", "Sensore termico"] },
];

export const MEMORY_WORDS_POOL = [
  "farfalla", "vulcano", "oceano", "foresta", "deserto", "ghiacciaio", "aurora", "tempesta", "corallo", "monsone",
  "galassia", "asteroide", "cometa", "nebulosa", "supernova", "satellite", "eclissi", "meteora", "pulsar", "quasar",
  "ornitorinco", "camaleonte", "fenicottero", "medusa", "pangolino", "axolotl", "narval", "quetzal", "okapi", "dugongo",
  "molecola", "neutrino", "fotosintesi", "magnetismo", "entropia", "isotopo", "catalisi", "osmosi", "fusione", "fissione",
  "origami", "mosaico", "calligrafia", "affresco", "terracotta", "ceramica", "papiro", "geroglifico", "mandala", "runa",
  "zafferano", "pistacchio", "melograno", "bergamotto", "cardamomo", "vaniglia", "cannella", "wasabi", "tartufo", "quinoa",
  "arcipelago", "penisola", "altopiano", "istmo", "fiordo", "tundra", "savana", "steppa", "delta", "oasi"
];

export const SPRINT_FACTS: Fact[] = [
  { text: "I polpi hanno 3 cuori", true: true },
  { text: "La Luna ha un'atmosfera", true: false },
  { text: "Le api possono contare fino a 4", true: true },
  { text: "L'oro è magnetico", true: false },
  { text: "I delfini dormono con un occhio aperto", true: true },
  { text: "I ragni hanno 6 zampe", true: false },
  { text: "Il miele non scade mai", true: true },
  { text: "Il vetro è un liquido", true: false },
  { text: "Le mucche hanno migliori amici", true: true },
  { text: "L'acqua calda gela più in fretta", true: true },
  { text: "I pesci non possono tossire", true: false },
  { text: "Le banane sono radioattive", true: true },
  { text: "La muraglia cinese si vede dallo spazio", true: false },
  { text: "I gatti hanno più ossa degli umani", true: true },
  { text: "Giove è una stella mancata", true: true },
  { text: "I diamanti sono indistruttibili", true: false },
  { text: "Le formiche non dormono mai", true: false },
  { text: "Il sangue dei granchi è blu", true: true },
  { text: "Il sole è una palla di fuoco", true: false },
  { text: "Le piante comunicano tra loro", true: true },
  { text: "L'Everest è il punto più lontano dal centro della Terra", true: false },
  { text: "I koala hanno impronte digitali", true: true },
  { text: "Cleopatra era egiziana", true: false },
  { text: "Le stelle marine non hanno cervello", true: true },
  { text: "I fenicotteri nascono rosa", true: false },
  { text: "Lo squalo è più vecchio degli alberi", true: true },
  { text: "La pioggia ha un odore perché è sporca", true: false },
  { text: "I corvi ricordano i volti umani", true: true },
  { text: "Venere ruota al contrario", true: true },
  { text: "I pinguini volano sott'acqua", true: true },
  { text: "Il deserto del Sahara è sempre stato arido", true: false },
  { text: "Le anguille elettriche sono pesci", true: false },
  { text: "L'universo ha un suono", true: true },
  { text: "Il cervello non sente dolore", true: true },
  { text: "I cammelli immagazzinano acqua nelle gobbe", true: false },
  { text: "Le ostriche cambiano sesso", true: true },
  { text: "Plutone è più piccolo della Luna", true: true },
  { text: "I serpenti sentono con la lingua", true: true },
  { text: "L'acciaio è più pesante del piombo", true: false },
  { text: "Le tartarughe respirano dal sedere", true: true },
  { text: "I vulcani esistono solo sulla Terra", true: false },
  { text: "Le lucciole sono fredde quando brillano", true: true },
  { text: "Il cuore umano batte circa 100.000 volte al giorno", true: true },
  { text: "I camaleonti cambiano colore per mimetizzarsi", true: false },
  { text: "I funghi sono più vicini agli animali che alle piante", true: true },
  { text: "La luce del sole impiega 8 secondi per arrivare", true: false },
  { text: "Le zebre sono bianche con strisce nere", true: false },
  { text: "L'acqua copre circa il 71% della Terra", true: true },
  { text: "I cani vedono in bianco e nero", true: false },
  { text: "Le farfalle assaggiano con i piedi", true: true },
  { text: "Il titanio è più leggero dell'alluminio", true: false },
  { text: "Le stelle cadenti sono stelle vere", true: false },
  { text: "Il bambù può crescere quasi un metro al giorno", true: true },
  { text: "I gatti sempre atterrano sulle zampe", true: false },
  { text: "La carta moneta è fatta di carta", true: false },
];

export const EMOJI_PUZZLES: EmojiPuzzle[] = [
  { emojis: ['🍎', '❤️', '🎓', '📚', '💼'], answer: 'scuola' },
  { emojis: ['👑', '🦁', '🌍', '🔥', '💪'], answer: 'potenza' },
  { emojis: ['☀️', '🌈', '🌻', '🌞', '✨'], answer: 'bellezza' },
  { emojis: ['🧠', '💡', '📖', '🎯', '🚀'], answer: 'genio' },
  { emojis: ['🌊', '🏖️', '🏄', '⛱️', '🌴'], answer: 'spiaggia' },
  { emojis: ['🎬', '🍿', '🎭', '🎪', '🎨'], answer: 'spettacolo' },
  { emojis: ['🍕', '🍝', '🇮🇹', '🍷', '👨‍🍳'], answer: 'italia' },
  { emojis: ['❄️', '⛄', '🎿', '🧊', '🌨️'], answer: 'inverno' },
  { emojis: ['🎵', '🎸', '🎹', '🎤', '🎧'], answer: 'musica' },
  { emojis: ['🚗', '⚡', '🏁', '💨', '🏎️'], answer: 'velocita' },
  { emojis: ['🌋', '🔥', '🏔️', '💨', '🌑'], answer: 'vulcano' },
  { emojis: ['🛸', '👽', '🌌', '🔭', '📡'], answer: 'alieno' },
  { emojis: ['🏰', '👸', '🐉', '⚔️', '🛡️'], answer: 'castello' },
  { emojis: ['🍔', '🍟', '🥤', '🍕', '🍦'], answer: 'cibo' },
  { emojis: ['⚽', '🏀', '🎾', '🏐', '🏈'], answer: 'sport' },
  { emojis: ['📱', '💻', '⌚', '📷', '🎧'], answer: 'tecnologia' },
  { emojis: ['🌳', '🌿', '🍃', '🍂', '🍁'], answer: 'natura' },
  { emojis: ['⛈️', '🌩️', '🌧️', '☔', '🌈'], answer: 'temporale' },
  { emojis: ['🎂', '🎈', '🎁', '🎉', '🎊'], answer: 'festa' },
  { emojis: ['🚂', '✈️', '🚢', '🚀', '🚁'], answer: 'viaggio' },
  { emojis: ['📖', '✏️', '📐', '🎒', '🏫'], answer: 'scuola' },
  { emojis: ['🐶', '🐱', '🐭', '🐹', '🐰'], answer: 'animali' },
  { emojis: ['🍎', '🍌', '🍇', '🍓', '🍍'], answer: 'frutta' },
  { emojis: ['🥦', '🥕', '🌽', '🍅', '🥔'], answer: 'verdura' },
  { emojis: ['🏠', '🏢', '🏨', '🏦', '🏥'], answer: 'citta' },
  { emojis: ['👔', '👗', '👕', '👖', '👟'], answer: 'vestiti' },
  { emojis: ['🕙', '📅', '⌛', '⏳', '⏰'], answer: 'tempo' },
  { emojis: ['💡', '🔦', '🕯️', '☀️', '🌟'], answer: 'luce' },
  { emojis: ['🔑', '🔒', '🔓', '🚪', '🏠'], answer: 'chiave' },
  { emojis: ['💎', '💍', '💰', '💳', '💵'], answer: 'ricchezza' },
  { emojis: ['🔨', '🔧', '🪚', '🪛', '🪜'], answer: 'attrezzi' },
  { emojis: ['🧪', '🧬', '🔬', '🔭', '⚗️'], answer: 'scienza' },
  { emojis: ['🎨', '🖌️', '🖍️', '🖼️', '🎭'], answer: 'arte' },
];
